name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest state
        uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: yarn install

#       - name: Build the project
#         run: yarn build

      - name: Generate static files for the project
        run: yarn generate
        
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: generated
          path: dist

  deploy:
    name: Deploy App
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest state
        uses: actions/checkout@v2.4.0
        
      - name: Download the build artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: generated
          path: dist

      - name: Deploy project using FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: public_html/



